import 'package:uuid/uuid.dart';
import '../models/post_model.dart';
import '../models/user_model.dart';
import '../theme/app_colors.dart';

const _uuid = Uuid();

// ─── Mock Users ──────────────────────────────────────────────────
final List<AppUser> mockUsers = [
  AppUser(
    id: 'user_me',
    username: 'you',
    avatarUrl: 'https://i.pravatar.cc/300?img=11',
    bio: 'Living in the moment ✨',
    followerIds: ['user_2', 'user_3', 'user_4'],
    followingIds: ['user_2', 'user_3', 'user_4', 'user_5'],
    postIds: ['post_own_1', 'post_own_2'],
  ),
  AppUser(
    id: 'user_2',
    username: 'aria.night',
    avatarUrl: 'https://i.pravatar.cc/300?img=5',
    bio: 'Photographer & dreamer 📷',
    followerIds: ['user_me', 'user_3'],
    followingIds: ['user_me'],
    postIds: ['post_1', 'post_4'],
  ),
  AppUser(
    id: 'user_3',
    username: 'kai.zen',
    avatarUrl: 'https://i.pravatar.cc/300?img=12',
    bio: 'Code. Coffee. Create.',
    followerIds: ['user_me', 'user_2'],
    followingIds: ['user_me', 'user_4'],
    postIds: ['post_2', 'post_5'],
  ),
  AppUser(
    id: 'user_4',
    username: 'luna.wave',
    avatarUrl: 'https://i.pravatar.cc/300?img=9',
    bio: 'Sunset chaser 🌅',
    followerIds: ['user_me', 'user_5'],
    followingIds: ['user_me', 'user_3'],
    postIds: ['post_3', 'post_6'],
  ),
  AppUser(
    id: 'user_5',
    username: 'nova.eclipse',
    avatarUrl: 'https://i.pravatar.cc/300?img=3',
    bio: 'Exploring the cosmos 🚀',
    followerIds: ['user_4'],
    followingIds: ['user_me'],
    postIds: ['post_7', 'post_8'],
  ),
];

// ─── Mock Posts ───────────────────────────────────────────────────
final List<Post> mockPosts = [
  Post(
    id: 'post_1',
    authorId: 'user_2',
    authorName: 'aria.night',
    authorAvatar: 'https://i.pravatar.cc/300?img=5',
    type: PostType.image,
    textContent: 'Golden hour at the coast 🌊',
    mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
  ),
  Post(
    id: 'post_2',
    authorId: 'user_3',
    authorName: 'kai.zen',
    authorAvatar: 'https://i.pravatar.cc/300?img=12',
    type: PostType.text,
    textContent: 'The best way to predict the future is to create it.',
    createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    gradientStart: AppColors.postGradients[0][0],
    gradientEnd: AppColors.postGradients[0][1],
  ),
  Post(
    id: 'post_3',
    authorId: 'user_4',
    authorName: 'luna.wave',
    authorAvatar: 'https://i.pravatar.cc/300?img=9',
    type: PostType.image,
    textContent: 'Chasing sunsets, always 🌅',
    mediaUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=800',
    createdAt: DateTime.now().subtract(const Duration(hours: 8)),
  ),
  Post(
    id: 'post_4',
    authorId: 'user_2',
    authorName: 'aria.night',
    authorAvatar: 'https://i.pravatar.cc/300?img=5',
    type: PostType.text,
    textContent: 'Every frame tells a story. What\'s yours?',
    createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    gradientStart: AppColors.postGradients[1][0],
    gradientEnd: AppColors.postGradients[1][1],
  ),
  Post(
    id: 'post_5',
    authorId: 'user_3',
    authorName: 'kai.zen',
    authorAvatar: 'https://i.pravatar.cc/300?img=12',
    type: PostType.image,
    textContent: 'Debug mode: OFF. Adventure mode: ON',
    mediaUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    createdAt: DateTime.now().subtract(const Duration(hours: 18)),
  ),
  Post(
    id: 'post_6',
    authorId: 'user_4',
    authorName: 'luna.wave',
    authorAvatar: 'https://i.pravatar.cc/300?img=9',
    type: PostType.text,
    textContent: 'Life begins at the edge of your comfort zone.',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    gradientStart: AppColors.postGradients[2][0],
    gradientEnd: AppColors.postGradients[2][1],
  ),
  Post(
    id: 'post_7',
    authorId: 'user_5',
    authorName: 'nova.eclipse',
    authorAvatar: 'https://i.pravatar.cc/300?img=3',
    type: PostType.image,
    textContent: 'The universe is under no obligation to make sense to you.',
    mediaUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800',
    createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
  ),
  Post(
    id: 'post_8',
    authorId: 'user_5',
    authorName: 'nova.eclipse',
    authorAvatar: 'https://i.pravatar.cc/300?img=3',
    type: PostType.text,
    textContent: 'We are all made of star stuff ✨',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    gradientStart: AppColors.postGradients[4][0],
    gradientEnd: AppColors.postGradients[4][1],
  ),
  Post(
    id: 'post_own_1',
    authorId: 'user_me',
    authorName: 'you',
    authorAvatar: 'https://i.pravatar.cc/300?img=11',
    type: PostType.text,
    textContent: 'Building something amazing today 🚀',
    createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    gradientStart: AppColors.postGradients[3][0],
    gradientEnd: AppColors.postGradients[3][1],
  ),
  Post(
    id: 'post_own_2',
    authorId: 'user_me',
    authorName: 'you',
    authorAvatar: 'https://i.pravatar.cc/300?img=11',
    type: PostType.image,
    textContent: 'Morning vibes ☀️',
    mediaUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
];

String generateId() => _uuid.v4();
